# Enhanced Unit Test CMakeLists.txt
cmake_minimum_required(VERSION 3.12)

add_subdirectory(constants)
add_subdirectory(numeric)
add_subdirectory(extension)
add_subdirectory(simd)
add_subdirectory(memory)
add_subdirectory(table)
add_subdirectory(reference)
add_subdirectory(control-flow)
add_subdirectory(variable)
