# Copyright (C) 2019 Intel Corporation.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

cmake_minimum_required(VERSION 3.14)

project(enhanced_feature_driven_ut)

# Enable testing
# enable_testing()

# Include common unit test configuration
# include(../unit_common.cmake)

# Add subdirectories for each module
add_subdirectory(aot)